@baseUrl = http://localhost:3333
@token = {{authenticate.response.body.token}}
@setCookie = {{authenticate.response.headers.set-cookie}}

###

# @name registerUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "first_name": "Teste",
  "last_name": "Teste",
  "user_name": "teste",
  "email": "teste@gmail.com",
  "password": "123456789",
  "role": "CLIENT"
}

###

# @name fetchUsers
GET {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name getUserById
GET {{baseUrl}}/users/49ee2df2-e01a-4e6e-8e34-601129f02b20
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name editUser
PATCH {{baseUrl}}/users/a86c1536-16e1-4116-89ed-abe71da0053e
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "first_name": "Lucas",
  "user_name": "lucassbgomes",
  "email": "lucas.sbgomes@gmail.com"
}

###

# @name deleteUser
DELETE {{baseUrl}}/users/ade09b7c-33eb-408e-a3ae-d133903b1a1e
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name authenticate
POST {{baseUrl}}/session
Content-Type: application/json

{
  "user_name": "teste",
  "password": "123456789"
}

###

# @name refreshToken
PATCH {{baseUrl}}/token/refresh
Cookie: {{setCookie}}

###

# @name getUserProfile
GET {{baseUrl}}/me
Content-Type: application/json
Authorization: Bearer {{token}}
